2025-02-20 00:40:39----------------------------------------------------------------
	[All]:
[OK]	first
[OK]	sec
[FAIL]	trid, Error: 2 + 3 != answ, expected: 5, got 4
[OK]	trid1
[OK]	third2
[FAIL]	third3, Error: 2 + 3 != answ, expected: 5, got 4
[OK]	testwithfix
[OK]	testwithfix1
[OK]	testwithfix2
[OK]	testcase( 1, 2, 3 )
[FAIL]	testcase( 1, 2, 4 ), Error: a + b != c, expected: 3, got 4
[FAIL]	testcase( 1, 2, 5 ), Error: a + b != c, expected: 3, got 5
[FAIL]	testcase( 1, 2, 6 ), Error: a + b != c, expected: 3, got 6
[OK]	testcase( 2, 2, 4 )
[OK]	testcase( 2, 2, 4 )
[OK]	testcase( 2, 2, 4 )
[OK]	testcase2( Vector(1, 1), Vector(1, 1) )
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
[FAIL]	datatestm, Error: val != 2, expected: 5, got 2
[FAIL]	datatestmgroup, Error: val != 2, expected: 1, got 2
[FAIL]	EPS, Error: Expected: |0 - 0.0001| < 0.00001, got: 0.0001 >= 1e-05
[FAIL]	EPS1, Error: Expected: |0 - 0.0001| < 0.0001, got: 0.0001 >= 0.0001
[OK]	EPS2
[FAIL]	EPS3, Error: Epsilon must be positive: -0.001
[FAIL]	point_rotate, Error: Epsilon must be positive: -1e-10
[OK]	MSGgood
[FAIL]	MSGbed, Error: Expected exception message: "error pem", but got: "error poblem"
[OK]	good1
[FAIL]	bed1, Error: Expected std::runtime_error, got a different exception.

	[g2] group: 
[OK]	sec
		OK 2 + 2 == 4
[FAIL]	trid, Error: 2 + 3 != answ, expected: 5, got 4
[OK]	trid1
		OK 2 + 2 == answ
[FAIL]	datatestmgroup, Error: val != 2, expected: 1, got 2
	[g2] complited: 2/4

	[g1] group: 
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
	[g1] complited: 3/4

	[exepct] group: 
[OK]	MSGgood
		OK std::invalid_argument error poblem
[FAIL]	MSGbed, Error: Expected exception message: "error pem", but got: "error poblem"
[OK]	good1
		OK std::invalid_argument
[FAIL]	bed1, Error: Expected std::runtime_error, got a different exception.
	[exepct] complited: 2/4
2025-02-20 00:46:15----------------------------------------------------------------
	[All]:
[OK]	first
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
		OK 2 + 2 == 4
[OK]	sec
		OK 2 + 2 == 4
[FAIL]	trid, Error: 2 + 3 != answ, expected: 5, got 4
[OK]	trid1
		OK 2 + 2 == answ
[OK]	third2
		OK 2 + 2 == answ
[FAIL]	third3, Error: 2 + 3 != answ, expected: 5, got 4
		OK 2 + 2 == answ
[OK]	testwithfix
		OK mega.x == 0
		OK mega.y == 10
[OK]	testwithfix1
		OK mega.x == 0
		OK mega.y == 10
[OK]	testwithfix2
		OK mega.x == 0
		OK mega.y == 10
[OK]	testcase( 1, 2, 3 )
		OK a + b == c
[FAIL]	testcase( 1, 2, 4 ), Error: a + b != c, expected: 3, got 4
[FAIL]	testcase( 1, 2, 5 ), Error: a + b != c, expected: 3, got 5
[FAIL]	testcase( 1, 2, 6 ), Error: a + b != c, expected: 3, got 6
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase2( Vector(1, 1), Vector(1, 1) )
		OK vec1 == vec2
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
[FAIL]	datatestm, Error: val != 2, expected: 5, got 2
		OK val == 2
		OK val == 2
		OK val == 2
		OK val == 2
[FAIL]	datatestmgroup, Error: val != 2, expected: 1, got 2
[FAIL]	EPS, Error: Expected: |0 - 0.0001| < 0.00001, got: 0.0001 >= 1e-05
[FAIL]	EPS1, Error: Expected: |0 - 0.0001| < 0.0001, got: 0.0001 >= 0.0001
[OK]	EPS2
		OK  |0 - 0.0001| < 0.001, 0.0001 < 0.001
[FAIL]	EPS3, Error: Epsilon must be positive: -0.001
[FAIL]	point_rotate, Error: Epsilon must be positive: -1e-10
[OK]	MSGgood
		OK std::invalid_argument error poblem
[FAIL]	MSGbed, Error: Expected exception message: "error pem", but got: "error poblem"
[OK]	good1
		OK std::invalid_argument
[FAIL]	bed1, Error: Expected std::runtime_error, got a different exception.

	[g2] group: 
[OK]	sec
		OK 2 + 2 == 4
[FAIL]	trid, Error: 2 + 3 != answ, expected: 5, got 4
[OK]	trid1
		OK 2 + 2 == answ
[FAIL]	datatestmgroup, Error: val != 2, expected: 1, got 2
	[g2] complited: 2/4

	[g1] group: 
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
	[g1] complited: 3/4

	[exepct] group: 
[OK]	MSGgood
		OK std::invalid_argument error poblem
[FAIL]	MSGbed, Error: Expected exception message: "error pem", but got: "error poblem"
[OK]	good1
		OK std::invalid_argument
[FAIL]	bed1, Error: Expected std::runtime_error, got a different exception.
	[exepct] complited: 2/4
2025-02-20 00:51:52----------------------------------------------------------------
	[g2] group: 
[OK]	sec
[FAIL]	trid, Error: 2 + 3 != answ, expected: 5, got 4
[OK]	trid1
[FAIL]	datatestmgroup, Error: val != 2, expected: 1, got 2
	[g2] complited: 2/4

	[g1] group: 
[OK]	testcase( 2, 2, 4 )
[OK]	testcase( 2, 2, 4 )
[OK]	testcase( 2, 2, 4 )
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
	[g1] complited: 3/4

	[exepct] group: 
[OK]	MSGgood
[FAIL]	MSGbed, Error: Expected exception message: "error pem", but got: "error poblem"
[OK]	good1
[FAIL]	bed1, Error: Expected std::runtime_error, got a different exception.
	[exepct] complited: 2/4
2025-02-20 00:54:03----------------------------------------------------------------
	[g2] group: 
[OK]	sec
		OK 2 + 2 == 4
[FAIL]	trid, Error: 2 + 3 != answ, expected: 5, got 4
[OK]	trid1
		OK 2 + 2 == answ
[FAIL]	datatestmgroup, Error: val != 2, expected: 1, got 2
	[g2] complited: 2/4

	[g1] group: 
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
	[g1] complited: 3/4

	[exepct] group: 
[OK]	MSGgood
		OK std::invalid_argument error poblem
[FAIL]	MSGbed, Error: Expected exception message: "error pem", but got: "error poblem"
[OK]	good1
		OK std::invalid_argument
[FAIL]	bed1, Error: Expected std::runtime_error, got a different exception.
	[exepct] complited: 2/4
2025-02-20 00:55:57----------------------------------------------------------------
	[g2] group: 
[OK]	sec
		OK 2 + 2 == 4
[FAIL]	trid, Error: 2 + 3 != answ, expected: 5, got 4
[OK]	trid1
		OK 2 + 2 == answ
[FAIL]	datatestmgroup, Error: val != 2, expected: 1, got 2
	[g2] complited: 2/4

	[g1] group: 
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
	[g1] complited: 3/4

	[exepct] group: 
[OK]	MSGgood
		OK std::invalid_argument error poblem
[FAIL]	MSGbed, Error: Expected exception message: "error pem", but got: "error poblem"
[OK]	good1
		OK std::invalid_argument
[FAIL]	bed1, Error: Expected std::runtime_error, got a different exception.
	[exepct] complited: 2/4
2025-02-20 00:56:11----------------------------------------------------------------
	[g2] group: 
[OK]	sec
		OK 2 + 2 == 4
[FAIL]	trid, Error: 2 + 3 != answ, expected: 5, got 4
[OK]	trid1
		OK 2 + 2 == answ
[FAIL]	datatestmgroup, Error: val != 2, expected: 1, got 2
	[g2] complited: 2/4

	[g1] group: 
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[OK]	testcase( 2, 2, 4 )
		OK a + b == c
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
[FAIL]	EPS, Error: Expected: |0 - 0.0001| < 0.00001, got: 0.0001 >= 1e-05
	[g1] complited: 3/5

	[exepct] group: 
[OK]	MSGgood
		OK std::invalid_argument error poblem
[FAIL]	MSGbed, Error: Expected exception message: "error pem", but got: "error poblem"
[OK]	good1
		OK std::invalid_argument
[FAIL]	bed1, Error: Expected std::runtime_error, got a different exception.
	[exepct] complited: 2/4

--------------------------------------------------------------------------------------------------------
-----------------------------------------2025-02-20 01:11:55-----------------------------------------
--------------------------------------------------------------------------------------------------------


	[g2] group: 
[OK]	sec
		OK 2 + 2 == 4, 4==4
[FAIL]	trid, Error: 2 + 3 != answ, expected: 5, got 4
		FAIL 2 + 3 != answ, expected: 5, got 4
[OK]	trid1
		OK 2 + 2 == answ, 4==4
[FAIL]	datatestmgroup, Error: val != 2, expected: 1, got 2
		FAIL val != 2, expected: 1, got 2
	[g2] complited: 2/4

	[g1] group: 
[OK]	testcase( 2, 2, 4 )
		OK a + b == c, 4==4
[OK]	testcase( 2, 2, 4 )
		OK a + b == c, 4==4
[OK]	testcase( 2, 2, 4 )
		OK a + b == c, 4==4
[FAIL]	testcase2( Vector(1, 1), Vector(2, 2) ), Error: vec1 != vec2, expected: (1, 1), got (2, 2)
		FAIL vec1 != vec2, expected: (1, 1), got (2, 2)
[FAIL]	EPS, Error: Expected: |0 - 0.0001| < 0.00001, got: 0.0001 >= 1e-05
		FAIL Expected: |0 - 0.0001| < 0.00001, got: 0.0001 >= 1e-05
	[g1] complited: 3/5

	[exepct] group: 
[OK]	MSGgood
		OK std::invalid_argument error poblem
[FAIL]	MSGbed, Error: Expected exception message: "error pem", but got: "error poblem"
		FAIL Expected exception message: "error pem", but got: "error poblem"
[OK]	good1
		OK std::invalid_argument
[FAIL]	bed1, Error: Expected std::runtime_error, got a different exception.
		FAIL Expected std::runtime_error, got a different exception.
	[exepct] complited: 2/4
